app/assets/stylesheets/custom.scss, app/uploaders/avatar_uploader.rb, app/views/profiles/show.html.erb
Pushing Joshua's new changes because on his branch we had the weird 2017 error that doesn't show up on mine
=> New CSS from Joshua

Gemfile.lock
Hey everyone - I think the two gems that had the security vulnerability should be up to date now.
=> Security vulnerability fixed

app/views/static_pages/search.html.erb
I changed to form to Bootstrap, added a neighborhood dropdown, made the Bootstrap search button, and added placeholder text
=> added bootstrap form and neighborhood dropdown

app/views/layouts/_header.html.erb, app/views/static_pages/search.html.erb
Made logo background transparent, logo image added to app/assets/images, put results on right side of the page
=> logo in header, results moved to right side of page

app/assets/stylesheets/custom.scss
Remove mayflower logo from fixed position in the middle of the webpage
=> remove logo from middle of page

app/assets/stylesheets/custom.scss, app/views/layouts/_header.html.erb
Changed navbar from <header> class to <navbar> class, also when you hover, the block around the links changes color. I chose some colors that look fine, but probably aren't what we actually want to use.
=> Increased font of navbar, and added hover blocks, changed colors

app/assets/stylesheets/custom.scss, app/views/layouts/_header.html.erb
Search is now the leftmost item in the navbar, colors for navbar are now blue & white
=> change navbar colors, moved search to the left

app/views/layouts/_header.html.erb
Also got rid of second half of logo
=> Replace mayflower logo with white version

app/assets/stylesheets/custom.scss, app/views/layouts/_header.html.erb, app/views/static_pages/search.html.erb
still need javascript for collapse, search now searches for nickname too, centered things and changed font family.
=> started collapse & modified search page

app/controllers/profiles_controller.rb, app/models/profile.rb, app/views/profiles/new.html.erb, config/routes.rb, db/seeds.rb
Added csv import capability to batch update profiles. Previous profiles must be deleted before importing new data to prevent duplicates
=> Csv import feature for batch update

app/controllers/profiles_controller.rb
* Correct redirect on failed save.
* Print out the fill details of the parameters.
* Permit an avatar field.  (That decision may need reconsideration.)
=> Updates to profiles controller.

app/controllers/profiles_controller.rb, app/views/profiles/new.html.erb, app/views/profiles/show.html.erb, config/initializers/carrierwave.rb
* Various changes to get CarrierWave to work.
* Update the show page to use the CarrierWave-chosen name for a file, rather than the "default" that the previous group chose.
=> Upload photos

app/controllers/profiles_controller.rb, app/views/profiles/edit.html.erb, app/views/profiles/new.html.erb, app/views/profiles/show.html.erb, db/migrate/20181116224603_add_biography_to_profiles.rb, db/schema.rb
Reverts CSC322-Grinnell/mayflower-directory#122
=> Revert "Draft biography"

app/assets/stylesheets/custom.scss, app/views/static_pages/home.html.erb
Resolves #135.
- Centered images properly
- Fixed layout issue on width only big enough for two links
1. Go to the resources tab
2. The resource images should be properly centered under the weather bar
3. Make sure it looks nice at all device widths
=> Fix resources layout

.github/pull_request_template.md
See [this article](https://help.github.com/en/articles/about-issue-and-pull-request-templates) for more about why we would want a pull request template.  Essentially, I just want to standardize the process.
=> Create pull request template to standardize PRs

app/views/users/edit_info.html.erb
#174 
Change the heading of Editing User Information from Reset User Info to Edit User Info
=> Change Reset Info to Edit

app/controllers/profiles_controller.rb
=> Change redirected view in destroy method to pictures

app/controllers/profiles_controller.rb, app/controllers/users_controller.rb, app/views/users/registrations/edit.html.erb
Resolves #195 
* Restrict a regular user from accessing URLs meant for admin accounts. 
* Delete Email field in "Change Your Password" 
* Log in as a regular user and try accessing /users and /users/edit paths (should not be successful). 
* Log in as an admin and test accessing those paths (should be successful)
* Try changing your own password at the Change Your Password site.
=> Restrict privileges

app/controllers/profiles_controller.rb, test/controllers/profiles_controller_test.rb, test/controllers/sessions_controller_test.rb, test/controllers/static_pages_controller_test.rb, test/controllers/users_controller_test.rb, test/fixtures/profiles.yml, test/fixtures/users.yml
- Refactored test fixtures to have more meaningful names
- Tests for the profiles controller now actually do something
- Cleaned up do-nothing and broken tests for other controllers
- Fixed bugs that became apparent when tests actually worked
1. Run `rails test`.  All tests should pass
2. Mess with profiles_controller.rb to break one of the things the tests say is supposed to work
3. Rerun `rails test`.  That test should fail
=> Fix profile tests

app/controllers/users_controller.rb, app/views/shared/_error_messages.html.erb, test/controllers/application_controller_test.rb, test/controllers/profiles_controller_test.rb, test/controllers/sessions_controller_test.rb, test/controllers/users_controller_test.rb, test/fixtures/users.yml, test/models/user_test.rb
- Fixed false passing tests on users controller
- Moved test that ensures users are signed in to the appropriate controller
- Added tests to make sure only admin users can mess with users
1. Run rails test. All tests should pass
2. Mess with users_controller.rb to break one of the things the tests say is supposed to work
3. Rerun rails test. That test should fail
4. Undo the change
5. Repeat from step 1 as needed
=> Fix user tests

app/assets/stylesheets/custom.scss, app/views/layouts/_header.html.erb, app/views/layouts/application.html.erb
- Top bar is now part of page flow, and will not overlap even when over-crowded
- Create profile/create user removed from top bar to reduce crowding
- Fix some font sizes to use rem
1. Start the server
2. Make sure the top bar looks good at all window sizes
=> Fix top bar styling

app/assets/stylesheets/profiles.scss
from justified to left justified, as client desired
*Does this pull request resolve any issues?  Delete this line and replace it with one that says Resolves #XXX where XXX is the issue number.*
- *A brief overview of the changes made.  Be sure to specify what pages and what part of the user experience is different*
1. *Steps for the reviewer to go through to verify that the changes are correct.  For example:*
2. Run `rails db:migrate`
3. Run `rails test`
4. Start the server and make sure page A has feature B
=> Changed staff bio alignment

app/views/departments/show.html.erb
changed department profile alignment
from justified to left
1. *Steps for the reviewer to go through to verify that the changes are correct.  For example:*
2. Run `rails db:migrate`
3. Run `rails test`
4. Start the server and make sure page A has feature B
=> changed department profile contact and description alignment
